### PR TITLE
Fixup #381: Wrong file edited

### PR DESCRIPTION
**Pull request by ktomk**
Changes in a4996d4 are overwritten by the build.

ref: a4996d48c6ce5932b4decb71b38712a981dc4cef

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
hmmm hole in my memory, this issue has been solved in another PR, right ?

**Comment by ktomk** [comment]
> hmmm hole in my memory, this issue has been solved in another PR, right ?

Yes, I kept the original PR number here as reference.

We did not solve it cause the wrong file edited (the generated one only).

just refreshed against master, but need to do again if I can trust this interface here while typing.

Let me take care.

**Comment by ktomk** [comment]
Refreshed against master.

**Comment by nvuillam** [comment]
Merged without the 40mn CI :D (bad practice but it's only MD so no risk)

At worse it will force me to update .cspell.json ^^

**Comment by ktomk** [comment]
yeah that .cspell.json ^^ 

I can also take a look.  let's see for whats next ... ^^

**Comment by nvuillam** [comment]
If you really have time.... https://github.com/nvuillam/mega-linter/issues/376

You could integrate your first linter in MegaLinter : https://github.com/todogroup/repolinter ;)

**Comment by ktomk** [comment]
@nvuillam what you say ^^  I wanted to make first of all my first linter and then I was thinking about to add PHP-CS-Fixer or others in the PHP section.

**Comment by nvuillam** [comment]
If you are a PHP guy, go for a PHP linter ;)
Just make sure that if there are several formatters/fixers , they don't fight between each other about the format ^^ (and if they do, you have to provide a variable to let the user choose a formatter, like with MARKDOWN_DEFAULT_STYLE :) )

**Pull request merged**
