### PR TITLE
Prevent `unexpected token` error on old node versions

### PR DESCRIPTION
**Pull request by joe-sharp**
I found this issue on a workstation I didn't realize had such an old version of node. If there is no interest in supporting old versions I am fine with abandoning this change. Only node v8.16.0 failed without this change (out of the versions I tested.) The following versions do not require this change; v10.16.1, v11.15.0, or v14.13.1

- On node v8.16.0 mega-linter-runner fails to run
- According to MDN the exception parameter can be omitted if unused but it doesn't appear to hurt anything on many versions of node
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#the_exception_identifier

## Proposed Changes

1. Add exception parameter to catch

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
Updated CHANGELOG

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by joe-sharp** [comment]
Not sure I understand the failure here. If you want to proceed with this PR can you please provide some direction on resolving the issue? Not sure if it is related but I did get an error trying to run `bash build.sh` before pushing.

**Comment by nvuillam** [comment]
What was the error when you run bash buid.sh ?

About the CI error, it's my fault, i'm on it ^^

**Comment by nvuillam** [comment]
@joe-sharp

-  i added a [pre-requisites section](https://nvuillam.github.io/mega-linter/contributing/#pre-requisites) in the documentation, processing it should make `bash build.sh` run properly :)

- I updated CI management from forks, please can you make your branch up to date with master branch and try again ? ( tip: write `quick build` in the latest commit message to run it faster )

- Please can you also update CHANGELOG ?

Thanks for your feedback :)

**Comment by joe-sharp** [comment]
> What was the error when you run bash buid.sh ?

Sorry about not already providing that. I was already away from the computer when I commented. Here is the error I am seeing:
```bash
  File "./.automation/build.py", line 47
    f"{REPO_HOME}/megalinter/descriptors/schemas/megalinter-descriptor.jsonschema.json"
                                                                                      ^
SyntaxError: invalid syntax
```
I reran the commands from the prerequisite section but I am still seeing the error.

**Comment by joe-sharp** [comment]
It looks like the issue may persist but I did have to push that subsequent merge commit separately from the `quick build` commit. I failed to merge my fork's master with yours before pushing. 🤦🏼

**Comment by nvuillam** [comment]
I think that you have an old python version, who does not support [f-strings](https://realpython.com/python-f-strings/)

Please can you try to install latest Python3 and try again ? :)

**Comment by nvuillam** [comment]
and about CI, there is still a bug on my side, sorry ^^

**Comment by joe-sharp** [comment]
> I think that you have an old python version, who does not support [f-strings](https://realpython.com/python-f-strings/)
> 
> Please can you try to install latest Python3 and try again ? :)

Will do, thanks! That seems like a likely issue. 😄

**Comment by nvuillam** [comment]
@joe-sharp I fixed the CI and tested it from a secondary account with a fork, it should be ok if now you merge nvuillam/mega-linter@master in your branch :)

**Comment by joe-sharp** [comment]
> @joe-sharp I fixed the CI and tested it from a secondary account with a fork, it should be ok if now you merge nvuillam/mega-linter@master in your branch :)

Thanks much, building now...

**Comment by joe-sharp** [comment]
> I think that you have an old python version, who does not support [f-strings](https://realpython.com/python-f-strings/)
> 
> Please can you try to install latest Python3 and try again ? :)

```
~/Documents/repos/mega-linter 🔮❯❯❯ python3 -V
Python 3.9.1
~/Documents/repos/mega-linter 🔮❯❯❯ bash build.sh
  File "./.automation/build.py", line 47
    f"{REPO_HOME}/megalinter/descriptors/schemas/megalinter-descriptor.jsonschema.json"
                                                                                      ^
SyntaxError: invalid syntax
```

**Comment by nvuillam** [comment]
Merged, thanks for your contribution :)
I'll release it tonight or tomorrow in an official version but can already use it in 50mn ( or in 10 if you use a Mega-Linter flavor) with insiders version :)

**Comment by nvuillam** [comment]
@joe-sharp 
hmmm as it is in the npm package, you can already try `npx mega-linter-runner@beta ....` :)

**Comment by joe-sharp** [comment]
Works perfectly!
```bash
~/Documents/repos/mega-linter 🔮❯❯❯ nvm use node 8.16.0
Now using node v8.16.0 (npm v6.14.5)
~/Documents/repos/mega-linter 🔮❯❯❯ npx mega-linter-runner -v
Unexpected token {
~/Documents/repos/mega-linter 🔮❯❯❯ npx mega-linter-runner@beta -v
mega-linter-runner version 4.26.1-beta202101252205.0
~/Documents/repos/mega-linter 🔮❯❯❯ nvm use node 14.13.1
Now using node v14.13.1 (npm v6.14.8)
~/Documents/repos/mega-linter 🔮❯❯❯ npx mega-linter-runner@beta -v
mega-linter-runner version 4.26.1-beta202101252205.0
```

**Pull request merged**
