### PR TITLE
Add config option for suppressing "Skipped Linters" output

### PR DESCRIPTION
**Pull request by ayyjohn**
Fixes # N/A

## Proposed Changes

1. add `SHOW_SKIPPED_LINTERS` option to `.mega-linter.yml` to let people suppress the following output
```
Skipped linters: ANSIBLE_ANSIBLE_LINT, ARM_ARM_TTK, BASH_EXEC, BASH_SHELLCHECK...
```
2. default the config option to `true` so nobody experiences a change without opting in
3. update documentation

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
Great , thanks for your contribution :)
I have an issue with SALESFORCE linters, I'll fix it then we'll be able to see if the CI errors are solved ^^

**Comment by ayyjohn** [comment]
> Great , thanks for your contribution :)
> I have an issue with SALESFORCE linters, I'll fix it then we'll be able to see if the CI errors are solved ^^

Ok! I thought I saw a test that this change may have affected, but I'll double check. I wouldn't expect to see anything fail since this should be a no-op until configs change but who knows!

**Comment by nvuillam** [comment]
I'm still working on salesforce test fixes, i'll post here when master will be ready to be merged in your branch :)

**Comment by nvuillam** [comment]
master should be ok now :)
-> merge master in your branch
-> merge conflict on jsonschema ( u can ignore the others)
-> build bash.sh
-> commit + push

**Comment by ayyjohn** [comment]
Ok, yeah it's actually failing. I'm unsure why, but it would be much easier if I could run the tests locally. It looks like that needs to be done in a docker container or similar. Is there documentation on how to run the tests locally for developers?

**Comment by nvuillam** [comment]
The failing tests are the one looking for "Skipped linters" in logs :)

You can reproduce by right clicking on test class with pycharm (but linter dependencies must be manually installed before)

**Comment by ayyjohn** [comment]
hmm... that would require installing all of them, and that's a lot. 
Any chance it can be run in a container? 

I'm sure it's just some simple issue that's causing it to default to suppressing the skipped linters output, but I'd love to be able to run them locally.

If not, maybe that could be something for me to do first: dockerize the tests. We've already got all the containers ready for that for when mega-linter itself is run.

**Comment by nvuillam** [comment]
Only the linters used by a test case are necessary , no need to install all of them :)
I'lm pretty sure that if you solve **test_enable_only_one_linter**, all other tests will pass.
And you just need eslint (that you probably already have) locally installed to run the test :)

**Comment by ayyjohn** [comment]
ah, got it! I had to install eslint globally. 
and yep! it was a silly bug because I was checking `== "true"` twice lol.

**Comment by nvuillam** [comment]
In python, to check if a variable is true, it is `is True` :)

Thanks for your contribution, I just merged :)

**Comment by ayyjohn** [comment]
wonderful! thanks :)

**Pull request merged**
