### PR TITLE
Use Python virtual-environment in dev-dependencies shell example

### PR DESCRIPTION
**Pull request by ktomk**
Just a small one to get hands warm.

### CODE REVIEW

**Comment by nvuillam** [comment]
CI is failing but it is because of a linter upgrade requiring to update test case ^^

Thanks for your contribution :)

**Comment by ktomk** [comment]
Found it, will fix it in a new PR.

**Comment by nvuillam** [comment]
my bad, I overriden your updates , just brought them back to master ^^

**Comment by ktomk** [comment]
no I edited the wrong file. if I would have read the comment in the first line .... :)

**Comment by ktomk** [comment]
see https://github.com/nvuillam/mega-linter/pull/385

**Comment by nvuillam** [comment]
Oh, you updated directly in docs folder haha ^^

**Pull request merged**
