### PR TITLE
Yamllint config

### LINKED ISSUE #742: [YAML_YAMLLINT] default config filename
Hello,

I found strange the default `yamllint` config filename defined on [descriptor](https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/yaml_yamllint.md#readme) page by  `YAML_YAMLLINT_CONFIG_FILE` variable  ( `.yaml-lint.yml`) 
 while official yamllint documentation specify other names (https://yamllint.readthedocs.io/en/stable/configuration.html).

Could you clarify the situation ?

### PR DESCRIPTION
**Pull request by llaville**
Fixes #742 

## Proposed Changes

rename default yamllint config filename from `.yaml-lint.yml` to `.yamllint.yml`

@nvuillam I've added another commit that include all files changed after runnin `build.sh --doc`; Hope it's ok (especially after my #745 question)

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
That looks great, thanks :)
I quickly add a new commit to rename the default config file name , and to solve the CI problem which is absolutely not related to your PR ^^

**Review by nvuillam — APPROVED** [review]
Good, thanks for your contribution :) ( I added some changes, and bypassed part of CI but it should be ok in master)

**Comment by llaville** [comment]
@nvuillam I'll take you aware that I think there are some regressions with YAML linters.
I've rebuilt locally full docker image with the last commit `8d1c429ed52c5155fc609e9c74154d5c76803af9`  (`docker build .`)

And I get some differences with YAML linters in JSON reporter. Checks in a part of report `status`, `status_code`, `stdout` (set to null)

```json
    "linters": [
        {
            "descriptor_id": "BASH",
            "descriptor_type": "language",
            "elapsed_time_s": 0.09354440000015529,
            "files": [
                "/tmp/lint/test/avail.sh",
                "/tmp/lint/test/meta.yml.sh",
                "/tmp/lint/test/readme.sh",
                "/tmp/lint/test/valid.sh"
            ],
            "files_lint_results": [
                {
                    "errors_number": 0,
                    "file": "/tmp/lint/test/avail.sh",
                    "fixed": false,
                    "status": "success",
                    "status_code": 0,
                    "stdout": ""
                }
            ],
            "files_number": 4,
            "is_active": true,
            "linter_name": "bash-exec",
            "name": "BASH_EXEC",
            "number_errors": 0,
            "number_fixed": 0,
            "return_code": 0,
            "status": "success",
            "total_number_errors": 0
        },
        {
            "descriptor_id": "BASH",
            "descriptor_type": "language",
            "elapsed_time_s": 0.2962351999999555,
            "files": [
                "/tmp/lint/test/avail.sh",
                "/tmp/lint/test/meta.yml.sh",
                "/tmp/lint/test/readme.sh",
                "/tmp/lint/test/valid.sh"
            ],
            "files_lint_results": [
                {
                    "errors_number": 1,
                    "file": "/tmp/lint/test/avail.sh",
                    "fixed": false,
                    "status": "error",
                    "status_code": 1,
                    "stdout": "\nIn /tmp/lint/test/avail.sh line 31:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 33:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 40:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 42:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 49:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 51:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 58:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 60:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\nFor more information:\n  https://www.shellcheck.net/wiki/SC2059 -- Don't use variables in the printf...\n"
                }
            ],
            "files_number": 4,
            "is_active": true,
            "linter_name": "shellcheck",
            "name": "BASH_SHELLCHECK",
            "number_errors": 4,
            "number_fixed": 0,
            "return_code": 1,
            "status": "error",
            "total_number_errors": 4
        },
        {
            "descriptor_id": "YAML",
            "descriptor_type": "format",
            "elapsed_time_s": 1.7796324000000823,
            "files": [
                "/tmp/lint/.mega-linter.yml",
                "/tmp/lint/flames/elastic/docker-compose.override.yml",
                "/tmp/lint/flames/elastic/meta.yml",
                "/tmp/lint/flames/revealjs/docker-compose.override.yml",
                "/tmp/lint/flames/revealjs/meta.yml",
                "/tmp/lint/flames/selenium/docker-compose.override.yml",
                "/tmp/lint/flames/selenium/meta.yml",
                "/tmp/lint/flames/stackedit/docker-compose.override.yml",
                "/tmp/lint/flames/stackedit/meta.yml",
                "/tmp/lint/flames/swaggerapi/docker-compose.override.yml",
                "/tmp/lint/flames/swaggerapi/meta.yml",
                "/tmp/lint/flames/webgrind/docker-compose.override.yml",
                "/tmp/lint/flames/webgrind/meta.yml"
            ],
            "files_lint_results": [
                {
                    "errors_number": null,
                    "file": "/tmp/lint/.mega-linter.yml",
                    "fixed": false,
                    "status": null,
                    "status_code": null,
                    "stdout": null
                }
            ],
            "files_number": 13,
            "is_active": true,
            "linter_name": "prettier",
            "name": "YAML_PRETTIER",
            "number_errors": 1,
            "number_fixed": 0,
            "return_code": 0,
            "status": "error",
            "total_number_errors": 1
        },
        {
            "descriptor_id": "YAML",
            "descriptor_type": "format",
            "elapsed_time_s": 0.26232160000017757,
            "files": [
                "/tmp/lint/.mega-linter.yml",
                "/tmp/lint/flames/elastic/docker-compose.override.yml",
                "/tmp/lint/flames/elastic/meta.yml",
                "/tmp/lint/flames/revealjs/docker-compose.override.yml",
                "/tmp/lint/flames/revealjs/meta.yml",
                "/tmp/lint/flames/selenium/docker-compose.override.yml",
                "/tmp/lint/flames/selenium/meta.yml",
                "/tmp/lint/flames/stackedit/docker-compose.override.yml",
                "/tmp/lint/flames/stackedit/meta.yml",
                "/tmp/lint/flames/swaggerapi/docker-compose.override.yml",
                "/tmp/lint/flames/swaggerapi/meta.yml",
                "/tmp/lint/flames/webgrind/docker-compose.override.yml",
                "/tmp/lint/flames/webgrind/meta.yml"
            ],
            "files_lint_results": [
                {
                    "errors_number": null,
                    "file": "/tmp/lint/.mega-linter.yml",
                    "fixed": false,
                    "status": null,
                    "status_code": null,
                    "stdout": null
                }
            ],
            "files_number": 13,
            "is_active": true,
            "linter_name": "yamllint",
            "name": "YAML_YAMLLINT",
            "number_errors": 1,
            "number_fixed": 0,
            "return_code": 1,
            "status": "error",
            "total_number_errors": 1
        }
    ]
```

**Comment by nvuillam** [comment]
@llaville what you call a regression is what I can a dramatic performance improvement :D 

I switched from file_by_file to list_of_files, so for example for Mega-Linter own linting -> 

Before:
image

After:
image

I'll provide a way to override lint mode (file by file , list of files or project) with configuration so u'll be able to have previous behaviour, but it will get you back to awful performances ^^

**Comment by llaville** [comment]
> @llaville what you call a regression is what I call dramatic performance improvement :D

I don't want to hurt you, but when I said there are regression, it's about results and not performance 👍 for this improvement !

Look at properties we get with other linters like BASH vs YAML into JSON REPORTER

BASH linter 
``` 
            "files_lint_results": [
                {
                    "errors_number": 1,
                    "file": "/tmp/lint/test/avail.sh",
                    "fixed": false,
                    "status": "error",
                    "status_code": 1,
                    "stdout": "\nIn /tmp/lint/test/avail.sh line 31:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 33:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 40:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 42:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 49:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 51:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 58:\n\tprintf \"${CLR_OK}[OK]${CLR_RST}  (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} found\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\n\nIn /tmp/lint/test/avail.sh line 60:\n\tprintf \"${CLR_ERR}[ERR]${CLR_RST} (avail)    ${CLR_TEST}${MY_FILE}${CLR_RST} not found in: ${FLAME}\\n\"\n               ^-- SC2059: Don't use variables in the printf format string. Use printf '..%s..' \"$foo\".\n\nFor more information:\n  https://www.shellcheck.net/wiki/SC2059 -- Don't use variables in the printf...\n"
                }
            ],

            "files_lint_results": [
                {
                    "errors_number": 0,
                    "file": "/tmp/lint/test/avail.sh",
                    "fixed": false,
                    "status": "success",
                    "status_code": 0,
                    "stdout": ""
                }
            ],
``` 

YAML linter
```
            "files_lint_results": [
                {
                    "errors_number": null,
                    "file": "/tmp/lint/.mega-linter.yml",
                    "fixed": false,
                    "status": null,
                    "status_code": null,
                    "stdout": null
                }
            ],

```

While previously we have `status: "success" or "error"`, `status_code: 0 or 1`, and `stdout: string or empty string`, now we have all values set to `null`

**Comment by nvuillam** [comment]
When cli_lint_mode is not `file` , files_lint_results has indeed much less meaning ^^

But if you really want to find that back, try `YAML_YAMLLINT_CLI_LINT_MODE: file` in your config file :)
Note: wait for this action to be completed so the build & upload of new docker image is complete -> https://github.com/nvuillam/mega-linter/runs/3645235870?check_suite_focus=true

**Comment by llaville** [comment]
> But if you really want to find that back, try `YAML_YAMLLINT_CLI_LINT_MODE: file` in your config file :)

👍 work like a charm ! (tested locally after rebuilt docker image)

**Comment by llaville** [comment]
Just one more question about values:

**yamllint** return warning about a file, and `status` is consider as `success`; of course its not an error, but could it be consider as warning ?
```
                {
                    "errors_number": 0,
                    "file": "/tmp/lint/flames/elastic/docker-compose.override.yml",
                    "fixed": false,
                    "status": "success",
                    "status_code": 0,
                    "stdout": "/tmp/lint/flames/elastic/docker-compose.override.yml\n  2:2       warning  missing starting space in comment  (comments)\n  3:1       warning  missing document start \"---\"  (document-start)\n\n"
                },

```

**Comment by nvuillam** [comment]
Mega-Linter does not manage warnings status for a linter, it's either success or failure, sorry :/

**Comment by llaville** [comment]
OK. Thanks for this answer

**Pull request merged**
