### PR TITLE
Added slither, a solidity linter

### PR DESCRIPTION
**Pull request by leogalbu**
Fixes #

## Proposed Changes

1. Implemented slither, a solidity linter

### CODE REVIEW

**Comment by leogalbu** [comment]
Hello,
in this draft pull request i added slither, a solidity linter

**Comment by leogalbu** [comment]
Hello,

In this draft pull request i added slither, a solidity linter.

**Comment by nvuillam** [comment]
@leogalbu why giving up ? :/

**Comment by leogalbu** [comment]
i did a mess with the request, :(

**Comment by nvuillam** [comment]
s**t happens ^^
Glad to see a new PR is coming :)

**Pull request closed without merging**
