### PR TITLE
Add example getting started doc to quick-start section

### LINKED ISSUE #395: Add link to linting doc with MegaLinter
Great article explaining how to lint documentation with Mega-Linter, by Alec Johnson ;)

https://www.ayyjohn.com/posts/linting

To add in documentation flavor page :)

### PR DESCRIPTION
**Pull request by ayyjohn**
Fixes #395 

## Proposed Changes

1. add a link to [this blog post](https://ayyjohn.com/posts/linting-a-jekyll-blog-with-mega-linter) to quick-start

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ayyjohn** [comment]
@nvuillam I wasn't sure where you'd want this, so feel free to propose a better place :)

**Comment by ayyjohn** [comment]
looks like it also fails cspell check because of `holdy` but I'm not married to that word by any means, so happy to re-word or add to .cspell ¯\_(ツ)_/¯

**Comment by nvuillam** [comment]
Please can you update cspell.json ?
You can also thank yourself in the special thanks section ;)

**Comment by ayyjohn** [comment]
> You can also thank yourself in the special thanks section ;)
that would feel so gratuitous, but I'm definitely interested in contributing further! 
I've got two features that I've been trying to figure out locally, and if they're not currently possible I'm definitely going to try to add them!

**Review by nvuillam — APPROVED** [review]
Thanks for your contribution :)

**Comment by nvuillam** [comment]
Remove draft status if you want me to merge :)

**Pull request merged**
