### PR TITLE
Upgrade clj kondo

### PR DESCRIPTION
**Pull request by evg-tso**
- Using the [latest clj-kondo tag](https://hub.docker.com/layers/cljkondo/clj-kondo/2021.08.06-alpine/images/sha256-db40727a4755d2585a616393e581aa9da65205dc7e085e0907c8ab638ec661a1?context=explore)
- Update relevant docs

### Author/Contributor
- [x ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by evg-tso** [comment]
It's odd that dependant didn't create PR by himself.  
I see that the [last commit](https://github.com/nvuillam/mega-linter/commit/3bccdd97dbe0401fad87f40940bbbdd1385583a0) in this area was by the bot.

**Comment by evg-tso** [comment]
Is the failure related to this PR?  

```
Run aquasecurity/trivy-action@master
/usr/bin/docker run --name bec5f551f56b4f47b47cd9f392b0995ffe974_0e87d8 --label 3bec5f --workdir /github/workspace --rm -e BUILD_DATE -e INPUT_IMAGE-REF -e INPUT_FORMAT -e INPUT_EXIT-CODE -e INPUT_IGNORE-UNFIXED -e INPUT_VULN-TYPE -e INPUT_SEVERITY -e INPUT_SCAN-TYPE -e INPUT_INPUT -e INPUT_SCAN-REF -e INPUT_TEMPLATE -e INPUT_OUTPUT -e INPUT_SKIP-DIRS -e INPUT_CACHE-DIR -e INPUT_TIMEOUT -e INPUT_IGNORE-POLICY -e INPUT_HIDE-PROGRESS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mega-linter/mega-linter":"/github/workspace" 3bec5f:551f56b4f47b47cd9f392b0995ffe974  "-a image" "-b table" "-c " "-d 1" "-e true" "-f os,library" "-g CRITICAL,HIGH" "-h " "-i docker.io/nvuillam/mega-linter:test-nvuillam-merge" "-j ." "-k " "-l " "-m " "-n " "-o " "-p true"
Running trivy with options:  --format  table --exit-code  1 --ignore-unfixed --vuln-type  os,library --severity  CRITICAL,HIGH --no-progress  docker.io/nvuillam/mega-linter:test-nvuillam-merge
Global options:  
2021-08-05T17:28:51.681Z	INFO	Need to update DB
2021-08-05T17:28:51.681Z	INFO	Downloading DB...
panic: BUG: Expected key start but instead found "", around line 1

 [recovered]
	panic: BUG: Expected key start but instead found "", around line 1
```

**Comment by evg-tso** [comment]
SIlly me, just noticed that #612 exists.  
Should I close this PR?

**Comment by nvuillam** [comment]
Dependabot changes Dockerfile but not the related flavor, that's why docker image based linters must be handled in a separate PR :)

Some breaking changes error has been pushed in Trivy, that's why it always failed now, I didn't find the time yet to solve the issue, so I bypass it for publications in master (but I'll solve it before releasing the next official Mega-Linter version)

**Comment by evg-tso** [comment]
Updated to 2021.08.06, rebased

**Pull request closed without merging**
