### PR TITLE
Fix terraform fmt & terragrunt hclfmt

### PR DESCRIPTION
**Pull request by tpansino**
## Proposed Changes

- Fixes the auto fix functionality of both `terraform fmt` and `terragrunt hclfmt`
- Adds tests to validate both
- (Bonus) Fix version number extraction for `terraform-fmt` and `rstfmt` (I think?)

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by tpansino** [comment]
@nvuillam , when you have a moment, can you confirm my version extraction fix is correct? I thought I had the regex set up correctly, but then looking at the generated docs it included extra text.

I don't see how to generate the `linter-versions.json` file myself, so I can't confirm if my fix worked. :sweat_smile:

**Comment by nvuillam** [comment]
Will do that today :)
About linter version & help, it generates itself with ci job "Auto update linters" , which is triggered daily + at each push in master :)

**Comment by nvuillam** [comment]
And to test locally, you can:
- install the related linter(s)
- run test class from vscode or pycharm

**Review by nvuillam — APPROVED** [review]
Many thanks for your contributions ;)

CI is passing, but fix is not tested by CI and version format neither, so please check with @latest / @insiders version if it's ok and submit another PR if not :)

**Pull request merged**
